server:
  port: 8083

spring:
  profiles:
    active: dev #prod #default
  jackson:
    deserialization:
      fail-on-unknown-properties: true
#  main:
#    allow-bean-definition-overriding: true#  mvc:#    throw-exception-if-no-handler-found: true#  web:#    resources:#      add-mappings: false

# Authentication Server Configurations
authentication:
  realmName: master
  keyUrl: https://iam-keycloak.neosofttech.com/auth/realms/

# InMemoryCache configs
cache-name: publicKeyCacheIngress
user-cache:
  name: userPermissionCacheIngress
  key: userPermissions
  view: viewPermission
  create: createPermission
  edit: editPermission
  delete: deletePermission

schedular-durations:
   public-key-update: 300000
   table-deletion: 0 15 8 * * ?
   column-deletion: 0 15 8 * * ?
   
   
